### ISSUE TITLE
Downloads fails for some bands

### ISSUE THREAD

**Issue by rapha8l** [catlinman/campdown#8] opened 2020-10-12 09:29 UTC
Thanks for your work !
It seems that band using accents fail to download, an example

```
campdown https://laere.bandcamp.com/album/solve                                                                                                           (/data/1/git-divers/bandcamp/bandcamp.sh (3))(11:17)

Detected Bandcamp album.

Laere - Solve
Traceback (most recent call last):
  File "/usr/sbin/campdown", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 73, in cli
    downloader.run()
  File "/usr/lib/python3.8/site-packages/campdown/__init__.py", line 203, in run
    album.download() if album.fetch() else False  # Start the download process if fetches succeeded.
  File "/usr/lib/python3.8/site-packages/campdown/album.py", line 224, in fetch
    if track.prepare():
  File "/usr/lib/python3.8/site-packages/campdown/track.py", line 177, in prepare
    info = json.loads(raw_info)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 3046 (char 3045)

```

**Comment by zealsprince** [comment] 2020-10-13 14:25
Duplicate of #6. Further details there but thanks for bringing it up!

**Closed as completed by zealsprince** 2020-10-13 14:25 UTC
Labels: duplicate
